baseurl: https://www.linkup.works
languageCode: ja-JP
theme: hugo-theme-stack
paginate: 5
title: 合同会社 Linkup

# GA Tracking ID
googleAnalytics: G-LE6DSE391M

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: ja

enableGitInfo: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - blog
    featuredImageField: image
    rssFullContent: true
    favicon: favicon.ico

    footer:
        since: 2020
        customText:

    dateFormat:
        published: 2006年 1月 2日
        lastUpdated: 2006年 1月 2日

    sidebar:
        emoji: 
        subtitle: 主にインフラ(サーバー、ミドルウェア)をメインに、SaaS 導入、Ruby(Rails)、Python(Django)を少々。広く浅くやってきました。
        avatar:
            local: true
            src: img/avatar.webp

    article:
        math: false
        toc: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: toyocy

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: about
          name: About
          url: /about
          weight: 100
          pre: user

        - identifier: blog
          name: Blog
          url: /blog
          weight: 200
          pre: note

        - identifier: store
          name: Store
          url: /store
          weight: 300
          pre: basket

        - identifier: archive
          name: Archive
          url: /archives
          weight: 400
          pre: archives

        - identifier: privacy-policy
          name: プライバシーポリシー
          url: /privacy-policy
          weight: 500
          pre: secure

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
    goldmark:
        renderer:
            unsafe: true