[[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

[[main]]
  name = "Blog"
  wight = 200
  identifier = "blog"
  url = "/blog/"

[[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"