copyright = "合同会社 Linkup, 2020-{{ YEAR }}"
profilePicture = "images/avatar.png"
favicon = "images/favicon"
readMore = true
postSectionName = "blog"
gtagId = "G-XXXXXXXXXX"
enable = true
singleDateFormat = "2006年 1月 2日"
indexDateFormat = "2006年 1月 2日"
listDateFormat = "1月 2日"
readingTime = true
socialShare = true

[[socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/takayuki-toyoshima/"

[[socialIcons]]
  icon = "fas fa-envelope"
  title = "e-mail"
  url = "mailto:toyoshima@linkup.works"